# Generated by Django 3.2.4 on 2023-09-21 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_enotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='enotes',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.studentbatch'),
        ),
    ]
