# Generated by Django 3.2.4 on 2023-09-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_enotes_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='batchid',
            field=models.IntegerField(null=True),
        ),
    ]
