# Generated by Django 3.2.4 on 2023-09-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_mytask_submittedtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mytask',
        ),
    ]
